# Generated by Django 5.1.4 on 2025-07-16 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0002_recreate_farmaco'),
        ('BioVitalAge', '0003_recreate_column_rischi'),
    ]

    operations = [
    ]
