# Generated by Django 5.1.4 on 2025-07-16 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0004_merge_20250716_1147'),
        ('BioVitalAge', '0005_add_problemi_to_diagnosi'),
    ]

    operations = [
    ]
