# Generated by Django 5.1.4 on 2025-07-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0006_merge_20250716_1158'),
        ('BioVitalAge', '0007_create_prescrizionefarmaco'),
    ]

    operations = [
    ]
