# Generated by Django 5.2.2 on 2025-07-21 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0002_prescrizionelibera'),
        ('BioVitalAge', '0008_merge_20250716_1203'),
    ]

    operations = [
    ]
