# Generated by Django 5.2.2 on 2025-08-07 09:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0009_merge_20250721_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visita_numero', models.IntegerField(blank=True, null=True)),
                ('data_visita', models.DateField(default=django.utils.timezone.now)),
                ('professione', models.CharField(blank=True, max_length=100, null=True)),
                ('pensionato', models.CharField(blank=True, max_length=100, null=True)),
                ('menarca', models.CharField(blank=True, max_length=100, null=True)),
                ('ciclo', models.CharField(blank=True, max_length=100, null=True)),
                ('sintomi', models.CharField(blank=True, max_length=100, null=True)),
                ('esordio', models.CharField(blank=True, max_length=100, null=True)),
                ('parto', models.CharField(blank=True, max_length=100, null=True)),
                ('post_parto', models.CharField(blank=True, max_length=100, null=True)),
                ('aborto', models.CharField(blank=True, max_length=100, null=True)),
                ('alcol', models.CharField(blank=True, max_length=255, null=True)),
                ('alcol_type', models.CharField(blank=True, max_length=255, null=True)),
                ('data_alcol', models.DateField(blank=True, null=True)),
                ('alcol_frequency', models.CharField(blank=True, max_length=255, null=True)),
                ('smoke', models.CharField(blank=True, max_length=255, null=True)),
                ('smoke_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('reduced_intake', models.CharField(blank=True, max_length=100, null=True)),
                ('sport', models.CharField(blank=True, default=False, max_length=100, null=True)),
                ('sport_livello', models.CharField(blank=True, max_length=100, null=True)),
                ('sport_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('attivita_sedentaria', models.CharField(blank=True, default=False, max_length=100, null=True)),
                ('livello_sedentarieta', models.CharField(blank=True, max_length=100, null=True)),
                ('sedentarieta_nota', models.TextField(blank=True, null=True)),
                ('m_cardiache', models.CharField(blank=True, max_length=100, null=True)),
                ('diabete_m', models.CharField(blank=True, max_length=100, null=True)),
                ('obesita', models.CharField(blank=True, max_length=100, null=True)),
                ('epilessia', models.CharField(blank=True, max_length=100, null=True)),
                ('ipertensione', models.CharField(blank=True, max_length=100, null=True)),
                ('m_tiroidee', models.CharField(blank=True, max_length=100, null=True)),
                ('m_polmonari', models.CharField(blank=True, max_length=100, null=True)),
                ('tumori', models.CharField(blank=True, max_length=100, null=True)),
                ('allergie', models.CharField(blank=True, max_length=100, null=True)),
                ('m_psichiatriche', models.CharField(blank=True, max_length=100, null=True)),
                ('patologie', models.CharField(blank=True, max_length=100, null=True)),
                ('p_p_altro', models.CharField(blank=True, max_length=100, null=True)),
                ('t_farmaco', models.CharField(blank=True, max_length=100, null=True)),
                ('t_dosaggio', models.CharField(blank=True, max_length=100, null=True)),
                ('t_durata', models.CharField(blank=True, max_length=100, null=True)),
                ('p_cardiovascolari', models.CharField(blank=True, max_length=100, null=True)),
                ('m_metabolica', models.CharField(blank=True, max_length=100, null=True)),
                ('p_respiratori_cronici', models.CharField(blank=True, max_length=100, null=True)),
                ('m_neurologica', models.CharField(blank=True, max_length=100, null=True)),
                ('m_endocrina', models.CharField(blank=True, max_length=100, null=True)),
                ('m_autoimmune', models.CharField(blank=True, max_length=100, null=True)),
                ('p_epatici', models.CharField(blank=True, max_length=100, null=True)),
                ('m_renale', models.CharField(blank=True, max_length=100, null=True)),
                ('d_gastrointestinali', models.CharField(blank=True, max_length=100, null=True)),
                ('eloquio', models.CharField(blank=True, max_length=100, null=True)),
                ('s_nutrizionale', models.CharField(blank=True, max_length=100, null=True)),
                ('a_genarale', models.CharField(blank=True, max_length=100, null=True)),
                ('psiche', models.CharField(blank=True, max_length=100, null=True)),
                ('r_ambiente', models.CharField(blank=True, max_length=100, null=True)),
                ('s_emotivo', models.CharField(blank=True, max_length=100, null=True)),
                ('costituzione', models.CharField(blank=True, max_length=100, null=True)),
                ('statura', models.CharField(blank=True, max_length=100, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=20, null=True)),
                ('rh_factor', models.CharField(blank=True, max_length=20, null=True)),
                ('pressure_min', models.CharField(blank=True, max_length=100, null=True)),
                ('pressure_max', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paziente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visite_paziente', to='BioVitalAge.tabellapazienti')),
            ],
        ),
    ]
