# Generated by Django 5.2.2 on 2025-08-07 10:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0010_visita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='data_visita',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='paziente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visite_paziente', to='BioVitalAge.tabellapazienti'),
        ),
    ]
