# Generated by Django 5.2.2 on 2025-09-08 10:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BioVitalAge', '0011_alter_visita_data_visita_alter_visita_paziente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resilienza',
            old_name='cortisolo',
            new_name='bp_dbp_mean',
        ),
        migrations.RenameField(
            model_name='resilienza',
            old_name='droms',
            new_name='bp_morning_surge',
        ),
        migrations.RenameField(
            model_name='resilienza',
            old_name='homa',
            new_name='bp_nocturnal_dip',
        ),
        migrations.RenameField(
            model_name='resilienza',
            old_name='hrv',
            new_name='bp_pp_calc',
        ),
        migrations.RenameField(
            model_name='resilienza',
            old_name='ir',
            new_name='bp_sbp_mean',
        ),
        migrations.RenameField(
            model_name='resilienza',
            old_name='nlr',
            new_name='bp_sd_dbp',
        ),
        migrations.RenameField(
            model_name='resilienza',
            old_name='omega_3',
            new_name='bp_sd_sbp',
        ),
        migrations.RenameField(
            model_name='resilienza',
            old_name='osi',
            new_name='holter_af_burden',
        ),
        migrations.RenameField(
            model_name='resilienza',
            old_name='pcr',
            new_name='holter_hr_max',
        ),
        migrations.RenameField(
            model_name='resilienza',
            old_name='ros',
            new_name='holter_hr_mean',
        ),
        migrations.RenameField(
            model_name='resilienza',
            old_name='vo2max',
            new_name='holter_hr_min',
        ),
        migrations.AddField(
            model_name='resilienza',
            name='data_misurazione',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='resilienza',
            name='holter_pac_hour',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resilienza',
            name='holter_pvc_hour',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resilienza',
            name='holter_st_events',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resilienza',
            name='hrv_hf_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resilienza',
            name='hrv_lf_hf',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resilienza',
            name='hrv_lf_power',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resilienza',
            name='hrv_pnn50',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resilienza',
            name='hrv_rmssd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resilienza',
            name='hrv_sdnn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resilienza',
            name='protocollo',
            field=models.CharField(choices=[('30m', '30 m'), ('60m', '60 m'), ('24h', '24 h')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='resilienza',
            name='selected_tests',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
